export const data = {
    registeredCandidates: [
      {
        id: '#1',
        name: 'Mei Mio',
        course: 'B.E',
        cgpa: 8,
        emailId: 'meimio@gmail.com',
        mobileNo: '9655383404',
        dob: '15/04/1999',
      },
      {
        id: '#2',
        name: 'Yuna Hina',
        course: 'B.Tech',
        cgpa: 6,
        emailId: 'yunahina@gmail.com',
        mobileNo: '9655383404',
        dob: '15/04/1999',
      },
      {
        id: '#3',
        name: 'Koharu Hinata',
        course: 'MCA',
        cgpa: 7,
        emailId: 'koharuhinata@gmail.com',
        mobileNo: '9655383404',
        dob: '15/04/1999',
      },
      {
        id: '#4',
        name: 'Saki Miyu',
        course: 'B.E',
        cgpa: 5,
        emailId: 'sakiMiyu@gmail.com',
        mobileNo: '9655383404',
        dob: '15/04/1999',
      },
      {
        id: '#5',
        name: 'Hayato Haruki',
        course: 'B.E',
        cgpa: 8,
        emailId: 'hayatoharuki@gmail.com',
        mobileNo: '9655383404',
        dob: '15/04/1999',
      },
      {
        id: '#6',
        name: 'Shan Haruki',
        course: 'B.E',
        cgpa: 8,
        emailId: 'shanharuki@gmail.com',
        mobileNo: '9655383404',
        dob: '15/04/1999',
      },
      {
        id: '#7',
        name: 'Shan Sheepu',
        course: 'B.E',
        cgpa: 8,
        emailId: 'shansheepu@gmail.com',
        mobileNo: '9655383404',
        dob: '15/04/1999',
      },
      {
        id: '#8',
        name: 'Veiku Shan',
        course: 'B.Tech',
        cgpa: 8,
        emailId: 'veikushan@gmail.com',
        mobileNo: '9655383404',
        dob: '15/04/1999',
      },
      {
        id: '#9',
        name: 'Veiku Ven',
        course: 'B.E',
        cgpa: 5,
        emailId: 'veikuven@gmail.com',
        mobileNo: '9655383404',
        dob: '15/04/1999',
      },
      {
        id: '#10',
        name: 'Pan Pu',
        course: 'MCA',
        cgpa: 6,
        emailId: 'panpu@gmail.com',
        mobileNo: '9655383404',
        dob: '15/04/1999',
      },
    ],
    technicalRound: [],
    hrRound: [],
    selectedCandidates: [],
  };
  
  export const courseLists = [
    { key: 'be', text: 'B.E', value: 'B.E' },
    { key: 'bTech', text: 'B.Tech', value: 'B.Tech' },
    { key: 'mca', text: 'MCA', value: 'MCA' },
  ];
  
  export const columnDatas = [
    { id: 'registeredCandidates', text: 'registered candidates', name: 'registeredCandidatesColumn' },
    { id: 'technicalRound', text: 'selected in technical round', name: 'technicalRoundColumn' },
    { id: 'hrRound', text: 'attended in hr round', name: 'hrRoundColumn' },
    { id: 'selectedCandidates', text: 'selected candidates', name: 'selectedCandidatesColumn' },
  ];